### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [imvickykumar999/Quantum-Qiskit#1]
I recently came across your project Quantum-Qiskit and I noticed that the repository github.com/imvickykumar999/Quantum-Qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by imvickykumar999** [comment]
Hi @cbjuan,

Thank you so much for bringing this to my attention and for guiding me regarding the importance of adding a license to my project! I truly appreciate your input.

I wasn't fully aware of the legal implications of not having a license file in the repository. As you've pointed out, having a proper open-source license like the Apache 2.0 license ensures that others can freely use, modify, and contribute to the project without any legal uncertainties. This is especially important to avoid any potential copyright issues and to make sure the project aligns with open-source principles.

I'll make sure to add a valid license to the repository as soon as possible, and your suggestion of using the Apache 2.0 license sounds perfect. Thanks again for guiding me on this, and for contributing to making this project better!

Best regards,  
@imvickykumar999

**Comment by cbjuan** [comment]
Thanks!
